### PR TITLE
Show error instead of exception when the text is not valid

### LINKED ISSUE #9707: [BOOM-5070] Iframe in custom text module
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5070).

- _**Reporter:**_ Comptoir Carrelage
- _**Created at:**_ Mon, 12 Mar 2018 11:00:59 +0100

<p>I have an error when I try to add an Iframe in custom text module when Iframe in HTML fields is disabled (Shop parameters > General)</p>

<p>I shouldn't have this error, it should be possible to add an iframe but it shouldn't be displayed in FO if Iframe in HTML fields is disabled.</p>

<p>We have this behavior in product page</p>

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | First, we properly handle exceptions. Secondly, we try to determine if merchants are trying to use `iframe` inside the content if they haven't enabled it yet
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#9707
| How to test?  | Disable "Allow iframe" in "Preferences -> General" and try to insert iframe inside the module. Before, and after this PR.
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_customtext/71)

### CODE REVIEW

**Comment by kpodemski** [comment]
Hello @Julievrz 

Do you think we could have this newly introduced phrase in the global domain? I can imagine using it outside of the `ps_customtext` module too.

File: ps_customtext.php [hunk 1]
```diff
@@ -205,14 +205,25 @@ public function processSaveCustomText()
 
         foreach ($languages as $lang) {
             $text[$lang['id_lang']] = (string) Tools::getValue('text_' . $lang['id_lang']);
+
+            if (!Configuration::get('PS_ALLOW_HTML_IFRAME') && preg_match('/<iframe.*src=\"(.*)\".*><\/iframe>/isU', $text[$lang['id_lang']])) {
+                $this->context->controller->errors[] = $this->trans('If you want to use <iframe> inside your content, enable them in Preferences -> General -> Allow iframes on HTML fields', [], 'Admin.Notifications.Error');
```
Comment (Julievrz) [inline ps_customtext.php:210]:
```suggestion
                $this->context->controller->errors[] = $this->trans('To use <iframe>, enable the feature in Shop Parameters> General', [], 'Admin.Notifications.Error');
```

Comment (Julievrz) [reply ps_customtext.php:210]: > Hello @Julievrz
> 
> Do you think we could have this newly introduced phrase in the global domain? I can imagine using it outside of the `ps_customtext` module too.

Yes, you can use 'Admin.Notifications.Error' :-)

**Review by Julievrz — APPROVED** [review]

File: ps_customtext.php (hunk 1 above)
Comment (kpodemski) [reply ps_customtext.php]: @Julievrz I added a space before `>`, unless you did that on purpose?

Comment (Julievrz) [reply ps_customtext.php]: Nope, it wasn't on purpose. Thanks, @kpodemski!

File: ps_customtext.php [hunk 2]
```diff
@@ -205,14 +205,25 @@ public function processSaveCustomText()
 
         foreach ($languages as $lang) {
             $text[$lang['id_lang']] = (string) Tools::getValue('text_' . $lang['id_lang']);
+
+            if (!Configuration::get('PS_ALLOW_HTML_IFRAME') && preg_match('/<iframe.*src=\"(.*)\".*><\/iframe>/isU', $text[$lang['id_lang']])) {
```
Comment (MeKeyCool) [inline ps_customtext.php:209]: Why using subpattern here `src=\"(.*)\"` ?
:thinking: I thought this expression should be used to extract a specific part of regex subject.

**Review by MeKeyCool — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @kpodemski ,

Thanks for the PR.

Before the PR :
Screenshot 2022-06-14 at 14 59 40

After installing the PR, I have no more exception. It is replaced by 2 error messages : 
Screenshot 2022-06-14 at 14 58 04

- Tested with the iframe option enabled and disabled.
- Tested with multiple iframes in the custom text block.
-> Front is well displayed.
- Switched back the iframe to NO. Front still shows the iframes until I configure again the module. The error messages are present.

it is QA ✅ 
Thanks!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @florine2623
